### ISSUE TITLE
UI for API ?

### ISSUE THREAD

**Issue by PivotalAnimal** [xyting/RigoFunc.IdentityServer#13]
Are you planning on creating a UI that uses the Account API to demonstrate a more complete solution? I like where you are going with this and may borrow some of your ideas. I am thinking of creating a management interface for IS4 based on the project I created, which uses others work too. SEE: https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore

**Comment by xyting** [comment]
@PivotalAnimal I had remove the Account API to [RigoFunc.Account](https://github.com/xyting/RigoFunc.Account) last night. I do that because I think the Account API is another abstraction about Asp.Net Core Identity.

**Comment by PivotalAnimal** [comment]
Cool. I'll leave that as a challenge to you. I was thinking of maybe creating a separate project similar to the IS4 SPA example. I like the openid js library @brochallen created. I also like Angular2 a lot. I might mix the two. The project I was thinking of creating would probably use same dll because both sites will be on the DMZ. Instead of calling across sites using CORS. Although I can see the need for that too.

**Comment by xyting** [comment]
Close this because the account api had been removed to  [RigoFunc.Account](https://github.com/xyting/RigoFunc.Account)
