### ISSUE TITLE
Upgrade to latest version of IdentityServer4

### ISSUE THREAD

**Issue by senzacionale** [xyting/RigoFunc.IdentityServer#23]
Can you please Upgrade to latest version of IdentityServer4?

**Comment by xyting** [comment]
@senzacionale OK, today later.

**Comment by senzacionale** [comment]
thank you

**Comment by xyting** [comment]
@senzacionale Upgraded byt commit @e68a22d and package [RigoFunc.IdentityServer/1.1.2](https://www.nuget.org/packages/RigoFunc.IdentityServer/1.1.2)

**Comment by xyting** [comment]
@senzacionale this issue can be closed now?

**Comment by senzacionale** [comment]
Yes you can close it. Thx
