### ISSUE TITLE
Get Clients and Scopes from database?

### ISSUE THREAD

**Issue by senzacionale** [xyting/RigoFunc.IdentityServer#26]
Hi,

do you have maybe a working project for IdentityServer4 where I can read Clients and Scopes from database? All my config is currently stored in DB.

Maybe with RigoFunc.IdentityServer.Services.EntityFrameworkCore?

regards,
Mitja

**Comment by PivotalAnimal** [comment]
Hi @senzacionale - You could try [this](https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore) out. There is a nuget package for it as well.

**Comment by ansaj777** [comment]
It would be nice if project author (@xyting) can provide some examples for reading Clients and Scopes from DB and not just from memory.

@PivotalAnimal nice project!

**Comment by ansaj777** [comment]
@xyting or anyone?

**Comment by ansaj777** [comment]
Can you give us some example how to implement `services.AddIdentityServerEntityFrameworkCoreServices?`

**Comment by xyting** [comment]
@ansaj777 U can use @PivotalAnimal nuget package, and I will impls it in a few days(this week)

**Comment by ansaj777** [comment]
@xyting nice to hear. I will wait for the implementation sample. Thank you

**Comment by ansaj777** [comment]
Can you maybe at the same time implement sample for Google external provider? Currently link has no implementation.

Thx

**Comment by lotosbin** [comment]
you can use IdentityServer and AspnetIdentity together.

https://www.processon.com/view/link/57b1834ee4b06764c1289a6f
![Uploading QQ截图20160815165944.png…]()

**Comment by senzacionale** [comment]
@xyting I am also looking forward to see this code (Clients and Scopes)

**Comment by xyting** [comment]
@senzacionale @ansaj777 The IdentityServer had have a repo [IdentityServer4.EntityFramework](https://github.com/IdentityServer/IdentityServer4.EntityFramework), maybe we SHOULD wait.

**Comment by ansaj777** [comment]
Hmm question is WHEN, if is in one or two months is to late :(

**Comment by xyting** [comment]
If more than this weekend, I'll provide one.

**Comment by ansaj777** [comment]
ok, good news

**Comment by ansaj777** [comment]
Something was commited in this project :)

https://github.com/IdentityServer/IdentityServer4.EntityFramework

**Comment by senzacionale** [comment]
can you provide an example?

**Comment by xyting** [comment]
@senzacionale Please wait IdentityServer4 RC nuget package

**Comment by ansaj777** [comment]
Will be EF included in IdentityServer4 RC?

**Comment by senzacionale** [comment]
IdentityServer4 EntityFramework RC1 will be release this week
