### ISSUE TITLE
Login with MsSQL form error

### ISSUE THREAD

**Issue by senzacionale** [xyting/RigoFunc.IdentityServer#28]
HI,

I added tables for 

> Microsoft.AspNetCore.Identity

, so now I have table like 

> AspNetUsers
> AspNetUserRoles

But from our implementation I always get
`
{"Error":{"Code":"Exception","Message":"Invalid object name 'Users'.","Target":null,"Details":[],"InnerError":null},"ErrorMessage":"Invalid object name 'Users'."}`

Why invalid name Users if table name should be AspNetUsers?

**Comment by xyting** [comment]
@senzacionale Maybe I SHOULD provide a better README.

**Comment by senzacionale** [comment]
Please add my fixes. You should have GUID and not int as key identifier


So change AppDbContext  to

```
public class AppDbContext : IdentityDbContext<AppUser, IdentityRole<Guid>, Guid>
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
           : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<AppUser>().ToTable("AspNetUsers");
            builder.Entity<IdentityRole<Guid>>().ToTable("AspNetRoles");
            builder.Entity<IdentityUserClaim<Guid>>().ToTable("AspNetUserClaims");
            builder.Entity<IdentityRoleClaim<Guid>>().ToTable("AspNetRoleClaims");
            builder.Entity<IdentityUserRole<Guid>>().ToTable("AspNetUserRoles");
            builder.Entity<IdentityUserLogin<Guid>>().ToTable("AspNetUserLogins");
            builder.Entity<IdentityUserToken<Guid>>().ToTable("AspNetUserTokens");
        }
    }
```

and AppUser  to 

```
public sealed class AppUser : IdentityUser<Guid> {
        public AppUser() { }

        public AppUser(string userName) : this() {
            UserName = userName;
        }
    }
```

and in StartUp.cs
```

services.AddIdentity<AppUser, IdentityRole<int>>(options => {
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
            })
            .AddEntityFrameworkStores<AppDbContext, int>()
.AddDefaultTokenProviders();
```

to

```
services.AddIdentity<AppUser, IdentityRole<Guid>>(options => {
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
            })
            .AddEntityFrameworkStores<AppDbContext, Guid>()
.AddDefaultTokenProviders();
```

**Comment by lotosbin** [comment]
@senzacionale project Host just a sample, direct use is not recommended.

**Comment by senzacionale** [comment]
@lotosbin why not if is a sample?

**Comment by xyting** [comment]
@senzacionale I had try your code, but haven't any problem.

**Comment by xyting** [comment]
@senzacionale I had commit @aaa8504, U should run `dotnet ef database update` under `Host` folder

**Comment by senzacionale** [comment]
I will try and let you know. Thank you for fast support!

**Comment by senzacionale** [comment]
Which context should I use?
`
More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands`

**Comment by xyting** [comment]
Maybe this link help [EF Command Line Reference](https://docs.efproject.net/en/latest/miscellaneous/cli/index.html)

**Comment by senzacionale** [comment]
right command is 

`dotnet ef database update -- context AppDbContext`
