### ISSUE TITLE
Google as External provider implementation

### ISSUE THREAD

**Issue by senzacionale** [xyting/RigoFunc.IdentityServer#29]
Like @Ansaj777 suggest, can you please implement external provider. I need it.

Currently Google link has no implementation. If is possible with

    UserManager

and not

    InMemoryUser

so with MsSQL.

**Comment by lotosbin** [comment]
@senzacionale  you can use IdentityServer and AspnetIdentity together.

https://www.processon.com/view/link/57b1834ee4b06764c1289a6f
![Uploading QQ截图20160815165944.png…]()

**Comment by senzacionale** [comment]
That I know. But I want to save new users if not exist then to databse.

So login with google for example and if user does not exist open register form ...

**Comment by senzacionale** [comment]
One more question to this topic. Is it possible with external provider for example Google get back Google token in JWT?
