### ISSUE TITLE
Reacting to back-end changes

### ISSUE THREAD

**Issue by xyting** [xyting/RigoFunc.IdentityServer#30]
The `User` had been updated after the `TOKEN` issued, the issued token `SHOULD` be discard and re-request a new one.

**Comment by lotosbin** [comment]
这个应该是使用refresh token 机制,
用户信息变更,使Token无效,客户端请求返回401时,尝试刷新token然后重新请求,
@xyting

**Comment by xyting** [comment]
是的，使原Token无效就好了

**Comment by xyting** [comment]
done
