### ISSUE TITLE
Update IdentityServer4 to  RC2

### ISSUE THREAD

**Issue by senzacionale** [xyting/RigoFunc.IdentityServer#31]
Hi,

when you will have time, can you update your project with new dependencies?

**Comment by senzacionale** [comment]
hi, do you have plan when you could make an update?

**Comment by ansaj777** [comment]
an news about the update?

**Comment by xyting** [comment]
We will update to [rc1-update2](https://www.nuget.org/packages/IdentityServer4/1.0.0-rc1-update2) soon

**Comment by ansaj777** [comment]
thank you.

**Comment by senzacionale** [comment]
How is going on with update?

**Comment by xyting** [comment]
@senzacionale yes

**Comment by ansaj777** [comment]
Is upgrade already finished?

**Comment by xyting** [comment]
Upgrading will be finished this weekend

**Comment by xyting** [comment]
@senzacionale @ansaj777 I had make some issues to IdentityServer4.AspNetIdentity, and they had fixed the issues. So maybe you can use the official  repo nuget package

**Comment by xyting** [comment]
Done, see [nuget package v1.2.0](https://www.nuget.org/packages/RigoFunc.IdentityServer/1.2.0)
