### ISSUE TITLE
split RigoFunc.IdentityServerServices.EntityFrameworkCore to sepreate repository ,or just remove it.

### ISSUE THREAD

**Issue by lotosbin** [xyting/RigoFunc.IdentityServer#35]

**Comment by xyting** [comment]
@lotosbin Maybe remove it better, we can PR to [IdentityServer4.EntityFramework](https://github.com/IdentityServer/IdentityServer4.EntityFramework) if have any new feature

**Comment by lotosbin** [comment]
@xyting need provider migration
